import json

def update_html_with_data(data):
    with open('berita.html', 'w') as html_file:
        html_file.write('<!DOCTYPE html>\n')
        html_file.write('<html lang="en">\n')
        html_file.write('<head>\n')
        html_file.write('<meta charset="UTF-8">\n')
        html_file.write('<meta name="viewport" content="width=device-width, initial-scale=1.0">\n')
        html_file.write('<title>Berita Terkini</title>\n')
        html_file.write('<link rel="stylesheet" href="css/style.css">\n')
        html_file.write('</head>\n')
        html_file.write('<body>\n')
        html_file.write('<header>\n')
        html_file.write('<nav>\n')
        html_file.write('<div class="logo">Zahra Hilyah</div>\n')
        html_file.write('<ul>\n')
        html_file.write('<li><a href="index.html">Home</a></li>\n')
        html_file.write('<li><a href="index.html">About</a></li>\n')
        html_file.write('<li><a href="index.html">Galery</a></li>\n')
        html_file.write('<li><a href="berita.html">Berita</a></li>\n')
        html_file.write('</ul>\n')
        html_file.write('<div class="menu-toggle">\n')
        html_file.write('<input type="checkbox">\n')
        html_file.write('<span></span>\n')
        html_file.write('<span></span>\n')
        html_file.write('<span></span>\n')
        html_file.write('</div>\n')
        html_file.write('</nav>\n')
        html_file.write('</header>\n')
        html_file.write('<div class="container">\n')
        html_file.write('<h1>DATA SCRAPING I</h1>\n')
        html_file.write('<table id="jsonTable" border="1">\n')
        html_file.write('<thead>\n')
        html_file.write('<tr>\n')
        html_file.write('<th>Judul</th>\n')
        html_file.write('<th>Kategori</th>\n')
        html_file.write('<th>Waktu Publish</th>\n')
        html_file.write('<th>Waktu Scraping</th>\n')
        html_file.write('</tr>\n')
        html_file.write('</thead>\n')
        html_file.write('<tbody>\n')
        for article in data:
            html_file.write('<tr>\n')
            html_file.write(f'<td>{article["judul"]}</td>\n')
            html_file.write(f'<td>{article["kategori"]}</td>\n')
            html_file.write(f'<td>{article["waktu_publish"]}</td>\n')
            html_file.write(f'<td>{article["waktu_scraping"]}</td>\n')
            html_file.write('</tr>\n')
        html_file.write('</tbody>\n')
        html_file.write('</table>\n')
        html_file.write('</div>\n')
        html_file.write('<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>\n')
        html_file.write('<script>\n')
        html_file.write('$(document).ready(function(){\n')
        html_file.write('$.getJSON("data.json", function(data){\n')
        html_file.write('$.each(data, function(index, item){\n')
        html_file.write('var row = "<tr>";\n')
        html_file.write('row += "<td>" + item.judul + "</td>";\n')
        html_file.write('row += "<td>" + item.kategori + "</td>";\n')
        html_file.write('row += "<td>" + item.waktu_publish + "</td>";\n')
        html_file.write('row += "<td>" + item.waktu_scraping + "</td>";\n')
        html_file.write('row += "</tr>";\n')
        html_file.write('$("#jsonTable tbody").append(row);\n')
        html_file.write('});\n')
        html_file.write('});\n')
        html_file.write('});\n')
        html_file.write('</script>\n')
        html_file.write('<div class="footer">\n')
        html_file.write('<p class="copy">\n')
        html_file.write('&copy Copyright 2024 by  <a href="#">PrkHlyaa</a>\n')
        html_file.write('</p>\n')
        html_file.write('</div>\n')
        html_file.write('</body>\n')
        html_file.write('</html>\n')

if __name__ == "__main__":
    with open('data.json') as json_file:
        data = json.load(json_file)
        update_html_with_data(data)
