name: Web Scraping

on:
  schedule:
    - cron: '*/2 * * * *' # Runs every 2 minutes

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Change to your Python version if needed

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run Web Scraping Script
      run: python scrape.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "PrkHlyaa"
        git config --global user.email "zahra19hilyatul@gmail.com"
        git add data.json
        git commit -m "Update data.json"
        git push
