name: Web Scraping

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' 

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: set GMT+7
      run: sudo timedatectl set-timezone Asia/Jakarta
    
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run Web Scraping Script
      run: python scrape.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "PrkHlyaa"
        git config --global user.email "zahra19hilyatul@gmail.com"
        git add .
        git commit -m "Update headline.json"
        git push
